### ISSUE TITLE
Mix of fixed and flexi grid DWDM networks

### ISSUE THREAD

**Issue by italobusi** [IETF-TEAS-WG/actn-poi#100]
Need to check how the WSON and Flexi-grid topology models can be used in case the DWDM network is a mix of fixed-grid and flexi-grid links

See comments in PR #92

**Comment by sergiobelotti** [comment]
> Need to check how the WSON and Flexi-grid topology models can be used in case the DWDM network is a mix of fixed-grid and flexi-grid links
> 
> See comments in PR #92

@italobusi : I remember a GMPLS draft extension proposed a signaling extension to manage this scenario and it seems to me there was a general agreement that the scenario is not probable at all .

**Comment by italobusi** [comment]
**[2022-11-22 ACTN POI Call (Slot 1)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-11-22.md)**

Jeff: we can also identify this as a gap of existing YANG models

**Comment by italobusi** [comment]
**[2022-11-29 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-11-29.md)**

Jeff: the fixed-grid network can be also managed using flexi-grid topology model and therefore the flexi-grid topology model can be used to manage fixed-grid, flexible-grid and mixed fixed-grid and flexible-grid DWDM networks

Italo: there are two issues when using the flexi-grid topology model for a fixed-grid network:
1) flexi-grid topology model can support multiple nominal central frequency granularity and slot width granularity values, so there are many options to describe the fixed-grid networks
2) the flexi-grid topology model cannot manage fixed-grid CWDM networks

We have agreed that issue 1) can be solved by using, as a convention, the 6.25GHz and 12.5GHz values for for nominal central frequency granularity and slot width granularity (which are the only standardized values in ITU-T G.694.1). The flexi-grid topology models allow different nominal central frequency granularity and slot width granularity values to co-exist within the same topology.

Jeff: CWDM networks are only for access and outside the scope of POI. Therefore the flexi-grid topology could be used for mixed-grid networks supporting POI.

It has been agreed to close this issue describing this approach.

- [ ] @italobusi update the draft to describe the use of flexi-grid topology for fixed-grid and mixed DWDM networks.

**Comment by italobusi** [comment]
Missing description of how the WSON and flexi-grid tunnel models can be used with a mix of fixed and flexi-grid DWDM networks
