### ISSUE TITLE
Security Considerations

### ISSUE THREAD

**Issue by italobusi** [IETF-TEAS-WG/actn-poi#41]
Provide text for the security considerations section

**Comment by danielkinguk** [comment]
Some initial text for security. 

>>
This document highlights how the ACTN architecture can deploy packet over optical infrastructure services. It highlights how existing IETF protocols and data models may be used for multi-layer services. It reuses several existing IETF protocols and data models for the MPI interfaces, between each PNC (Optical or Packet) and the MDSC. 

A variety of MPI protocols and data models are highlighted in this document, including:

-	RESTCONF: 
-	NETCONF
-	YANG
-	PCEP

Several existing security practices and techniques may be used to help secure those MPI interfaces. The usage of Transport Layer Security (TLS) to provide secure transport for RESTCONF, NETCONF and PCEP, is recommended. 
<<

I will continue to work on this text.

**Comment by italobusi** [comment]
**[2023-07-04 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2023-07-04.md)**

Prasenjit has reviewed the proposed text and he thinks it is ok

- [ ] @italobusi include the text proposed by Daniel in the PR #114
