### ISSUE TITLE
Operational Considerations

### ISSUE THREAD

**Issue by italobusi** [IETF-TEAS-WG/actn-poi#42]
Provide some short text for the operational considerations.

**Comment by danielkinguk** [comment]
Suggested text, although I will polish further. 

>>
This document has identified the need and enabling components for automating the management and control of multi-layer Service Providers' transport networks, combining the optical and microwave transport layer with the packet (IP/MPLS) layer to create a more efficient and scalable network infrastructure. This approach is particularly beneficial for Service Providers and large enterprises dealing with high bandwidth demands and looking for cost-effective ways to expand their networks. However, integrating these two traditionally separate network layers involves several operational considerations:   

o Network Design and Capacity Planning: Deciding the degree of integration between the packet and optical layers is critical. Furthermore, this includes determining whether to pursue a loose integration (keeping layers distinct but coordinated) or a tight integration (combining layers more closely, potentially at the hardware level) coordinated via the MDSC. Accurate forecasting and planning will also be essential to ensure that the integrated ACTN infrastructure can handle future capacity demand without excessive over-provisioning;

o System Interoperability: Networks often comprise equipment from various vendors. Ensuring that packet and optical devices can interoperate seamlessly and the PNCs can manage them is crucial for a successful integration. The Service Provider must also check with the vendors to ensure they support the IETF-based technologies outlined in this document; 

o Performance Monitoring: The integrated POI network will require comprehensive monitoring solutions that can provide visibility to the PNCs across both packet and optical layers. Identifying and diagnosing issues may become more complex with integrated layers. Telemetry data may also be required to collect lower-layer networking health and consider network and service performance. This topic is further discussed in [ACTN Assurance];

o Fault Management and Recovery: The POI networks should be resilient, including considerations for automatic protection switching and fast reroute mechanisms that span both layers. Fault isolation and recovery may become more challenging, as issues in one layer can have cascading effects on the other. Effective fault management strategies must be in place to quickly identify and rectify such issues. This topic is further discussed in [ACTN Assurance];

Specific Security Considerations are discussed in Section 7. 
<<

**Comment by ggrammel** [comment]
Hi Dan,

I got a little confused about the use of the term “Layer” and tried to figure out which definition has been used. CCAMP once produced RFC4397<https://datatracker.ietf.org/doc/rfc4397/> but it isn’t referenced in ACTN. It would ease the understanding to have it added to keep definitions aligned.

Best

Gert



Juniper Business Use Only

From: danielkinguk ***@***.***>
Date: Tuesday, 13. February 2024 at 10:16
To: IETF-TEAS-WG/actn-poi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [IETF-TEAS-WG/actn-poi] Operational Considerations (#42)
[External Email. Be cautious of content]


Suggested text, although I will polish further.

This document has identified the need and enabling components for automating the management and control of multi-layer Service Providers' transport networks, combining the optical and microwave transport layer with the packet (IP/MPLS) layer to create a more efficient and scalable network infrastructure. This approach is particularly beneficial for Service Providers and large enterprises dealing with high bandwidth demands and looking for cost-effective ways to expand their networks. However, integrating these two traditionally separate network layers involves several operational considerations:

o Network Design and Capacity Planning: Deciding the degree of integration between the packet and optical layers is critical. Furthermore, this includes determining whether to pursue a loose integration (keeping layers distinct but coordinated) or a tight integration (combining layers more closely, potentially at the hardware level) coordinated via the MDSC. Accurate forecasting and planning will also be essential to ensure that the integrated ACTN infrastructure can handle future capacity demand without excessive over-provisioning;

o System Interoperability: Networks often comprise equipment from various vendors. Ensuring that packet and optical devices can interoperate seamlessly and the PNCs can manage them is crucial for a successful integration. The Service Provider must also check with the vendors to ensure they support the IETF-based technologies outlined in this document;

o Performance Monitoring: The integrated POI network will require comprehensive monitoring solutions that can provide visibility to the PNCs across both packet and optical layers. Identifying and diagnosing issues may become more complex with integrated layers. Telemetry data may also be required to collect lower-layer networking health and consider network and service performance. This topic is further discussed in [ACTN Assurance];

o Fault Management and Recovery: The POI networks should be resilient, including considerations for automatic protection switching and fast reroute mechanisms that span both layers. Fault isolation and recovery may become more challenging, as issues in one layer can have cascading effects on the other. Effective fault management strategies must be in place to quickly identify and rectify such issues. This topic is further discussed in [ACTN Assurance];

Specific Security Considerations are discussed in Section 7.
<<

**Comment by danielkinguk** [comment]
That's a great comment. Thanks Gert, I will update.

**Comment by italobusi** [comment]
**[2024-06-11 ACTN POI ad-hoc call](https://github.com/IETF-TEAS-WG/actn-poi/wiki/minutes-2024-06-11)**

Italo, Sergio and Jeff have reviewed the proposal and they are ok with the proposed text

- [ ] @italobusi check offline with  @danielkinguk how to address the comment from Gert

Jeff noted that optical path setup also involves planning and validation steps

- [ ] @italobusi  check offline with  @danielkinguk how to describe this point in the Operational Considerations

- [ ]  @italobusi update the text in PR #118 based on the offline discussion with  @danielkinguk

**Comment by danielkinguk** [comment]
Hi All, updated text to address the good comments from Gert. 

>>
Automating the management of complex service provider networks is critical for meeting growing bandwidth demands and delivering new services efficiently. This document explores the need for automation in multi-layer transport networks, where a “layer” refers to a specific level of functionality within the network architecture and the term is further defined in [RFC4397]. Service providers can create a more efficient and scalable network infrastructure by automating the management and control of these layers, including the optical and microwave transport layers and the packet (IP/MPLS) layer. For instance, automating traffic routing across these layers can enable dynamic allocation of resources, ensuring optimal network performance for various applications.

This approach is particularly beneficial for Service Providers and large enterprises dealing with high bandwidth demands and looking for cost-effective ways to expand their networks. However, integrating multiple network layers involves several operational considerations: 
	
o Network Design and Capacity Planning: Deciding the degree of integration between the packet and optical layers is critical. Furthermore, this includes determining whether to pursue a loose integration (keeping layers distinct but coordinated) or a tight integration (combining layers more closely, potentially at the hardware level) coordinated via the MDSC. Accurate forecasting and planning will also be essential to ensure that the integrated ACTN infrastructure can handle future capacity demand without excessive over-provisioning; 

o System Interoperability: Networks often comprise equipment from various vendors. Ensuring that packet and optical devices can interoperate seamlessly and the PNCs can manage them is crucial for successful integration. The Service Provider must also check with the vendors to ensure they support the IETF-based technologies outlined in this document; 

o Performance Monitoring: The integrated POI network will require comprehensive monitoring solutions that can provide visibility to the PNCs across both packet and optical layers. Identifying and diagnosing issues may become more complex with integrated layers. Telemetry data may also be required to collect lower-layer networking health and consider network and service performance. This topic is further discussed in [ACTN Assurance]; 

o Fault Management and Recovery: The POI networks should be resilient, including considerations for automatic protection switching and fast reroute mechanisms that span both layers. Fault isolation and recovery may become more challenging, as issues in one layer can have cascading effects on the other. Effective fault management strategies must be in place to quickly identify and rectify such issues. This topic is further discussed in [ACTN Assurance]; 

Finally, securing the layered network will be critical and specific Security Considerations are discussed in Section 7.
<<
