### ISSUE TITLE
SR-TE traffic steering on a device

### ISSUE THREAD

**Issue by italobusi** [IETF-TEAS-WG/actn-poi#72]
**[2021-11-23 ACTN POI Call (Slot 1)
](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2021-11-23.md)**

Analyze some examples of how SR-TE traffic steering works on a device to understand which information is required at the MPI

**Comment by jbrentfoster** [comment]
Attached slides reviewed on today's call

Also, here is link to Cisco docs for this:
https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k-r7-0/segment-routing/configuration/guide/b-segment-routing-cg-asr9000-70x/b-segment-routing-cg-asr9000-70x_chapter_01000.html#id_128905

This is covered exhaustively in section 8 of draft-ietf-spring-segment-routing-policy
https://datatracker.ietf.org/doc/html/draft-ietf-spring-segment-routing-policy-08#section-8

8.4 Per-Destination Steering
[SRTE_steering.pptx](https://github.com/FabioPeruzzini/actn-poi/files/8026188/SRTE_steering.pptx)

would be the preferred mechanism for this use-case

**Comment by italobusi** [comment]
**2022-02-08 ACTN POI Call (Slot 2)**

Brent's presentation: https://github.com/FabioPeruzzini/actn-poi/issues/72#issuecomment-1032884525

Oscar: there are YANG models defined in IETF for the device configuration but it is not precluded to use them at the NBI of a controller:
- routing policy: https://datatracker.ietf.org/doc/html/rfc9067
- BGP standard community: https://datatracker.ietf.org/doc/html/draft-ietf-idr-bgp-model

In L3NM, some placeholder for policies have been left. The typical use of route policies is to accept or reject routes but they could also be used to set the standard community colors.

An alternative approach could be to infer the policy from the TE service mapping configuration, but the TSM does not allow fine graine policy configuration: only one SR policy can be configured for each pair of PEs

- [ ] @oscargdd @jbouqui153 : further investigate which model could be applied at the MPI

**Comment by italobusi** [comment]
[**2022-02-22 ACTN POI Call (Slot 2)**](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-02-22.md)

> * [ ]  @oscargdd @jbouqui153 : further investigate which model could be applied at the MPI

Jeff reported some concerns that the per-prefix method of steering L3VPN traffic to an SR policy (“ODN”) does not apply to all scenarios (such as L2 pseudowire).

Brent: For L2 pseudowire we have another configuration to set the “preferred-path”.  I have included this example in the slides I reviewed last time.

The “common denominator” between L2VPN and L3VPN would be simply configuring a static route that directs all traffic (L2VPN or L3VPN) to a remote PE loopback address.  However, this is not providing granular control and I would not recommend it.

**Comment by italobusi** [comment]
**[2022-05-17 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-05-17.md)**

> * [x]  @oscargdd @jbouqui153 : further investigate which model could be applied at the MPI

With EVPN it is possible to have a common mechanism, based on BGP, between L2VPN and L3VPN. The "preferred-path" option is only required for traditional L2VPN based on T-LDP.

Need to further investigate the information required at the MPI to drive this configuration.

- [ ] @italobusi : check offline with Oscar

An alternative approach could say that it is assumed that the L2VPN and L3VPN is properly configured to steer the traffic to a given policy by mechanisms which are outside the scope of this draft.

**Comment by italobusi** [comment]
**[2022-11-14 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-11-15.md)**

> * [x]  @italobusi : check offline with Oscar

The analysis in https://github.com/FabioPeruzzini/actn-poi/issues/72#issuecomment-1133725574 has been agreed

The configuration of the steering for L2VPN or L3VPN to a TE tunnel at the MPI is performed using the TE service mapping model. The P-PNC will translate this configuration to a proper device configuration, such as a BGP policy.

- [ ] @italobusi @oscargdd : check with Dhruv is there are gaps in the current TE service mapping (e.g., granularity) to be documented in this draft

**Comment by italobusi** [comment]
> [x] @italobusi @oscargdd : check with Dhruv is there are gaps in the current TE service mapping (e.g., granularity) to be documented in this draft

Feedbacks from the discussion with Dhruv:
- the TSM augmentations to the L2NM/L3NM YANG model define a list of TE tunnel(s) that should be used to forward L2VPN/L3VPN traffic between the two PEs terminating the listed TE tunnel(s);
- the list of TE tunnel(s) defined in TSM can contain more than one TE tunnel for the same PE pair and that in this case load balancing is used to forward the L2VPN/L3VPN traffic between two PEs through all these TE tunnels.

**Comment by italobusi** [comment]
**[2022-12-13 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-12-13.md)**

Feedbacks from the discussion with Dhruv:

https://github.com/FabioPeruzzini/actn-poi/issues/72#issuecomment-1335063430

Oscar: we can document what can be done with the current model. The question for the team is whether this is sufficient or if there is a need to split the traffic in different ways (more granular than load balancing) between multiple parallel tunnels. We can document this behavior and the identified gap.

Italo/Brent: How the P-PNC configures the PE devices toward the proper TE tunnel(s) is outside the scope of this document.

Oscar: I would like to work on a draft addressing this gap but this is outside the scope of this work.

- [ ] @italobusi : update the draft based on this analysis
