### ISSUE TITLE
Protection options with SR-TE

### ISSUE THREAD

**Issue by italobusi** [IETF-TEAS-WG/actn-poi#80]
In section 4.2.3, it is said that the MDSC configures TI-LFA for a given SR-TE path. However, TI-LFA is pre-configured by the P-PNC for local protection, independently from the SR-TE paths. An unprotected adjacency SID can be used if TI-LFA local protection is not required.

- [x] Brent: to provide some text for section 4.2.3 about the protection options: to be further discussed whether to place this text in section 4.2.3 or in section 2.2.2

_Originally posted by @italobusi in https://github.com/FabioPeruzzini/actn-poi/issues/69#issuecomment-1048125960_

**Comment by jbrentfoster** [comment]
I would suggest the following text referencing RFC 9256:

In addition to TI-LFA, [RFC 9256 section 9] describes additional mechanisms for protection.  A dedicated backup policy can be instantiated for local protection and configured for fast-reroute [section 9.2]. Or, an additional candidate path within the SR Policy can be configured as a backup with various options for path protection [section 9.3].

**Comment by italobusi** [comment]
**[2023-01-10 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2023-01-10.md)**

> * [x]  Brent: to provide some text for section 4.2.3 about the protection options: to be further discussed whether to place this text in section 4.2.3 or in section 2.2.2

The text proposed in https://github.com/FabioPeruzzini/actn-poi/issues/80#issuecomment-1377399770 has been reviewed and agreed. It may be useful to add also similar text for MPLS-TE and generalize the description (in line with the discussion in issue #88)

- [ ] @jbrentfoster provide a similar text proposal for the MPLS-TE case

**Comment by jbrentfoster** [comment]
The primary protection option for MPLS RSVP-TE tunnels is Fast Reroute (FRR) for local protection, which rapidly switches traffic to pre-established backup tunnels upon failure detection [RFC 4090]. Another option is end-to-end protection using secondary LSPs, where backup paths are predefined and can be activated when the primary path fails [RFC 3209].

**Comment by italobusi** [comment]
**[2024-06-11 ACTN POI ad-hoc call](https://github.com/IETF-TEAS-WG/actn-poi/wiki/minutes-2024-06-11)**

Brent will provide a short description for the MPLS-TE protection option by the end of this week
