### ISSUE TITLE
Standard reference for TI-LFA local protection

### ISSUE THREAD

**Issue by italobusi** [IETF-TEAS-WG/actn-poi#95]
Shouldn't be a reference standard for TI-LFA local protection?

_Originally posted by @sergiobelotti in https://github.com/FabioPeruzzini/actn-poi/pull/94#discussion_r912733844_

**Comment by italobusi** [comment]
**[2022-09-20 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-09-20.md)**

Brent will add reference to TI-LFA and update the comment

**Comment by jbrentfoster** [comment]
Here is the reference:
https://datatracker.ietf.org/doc/html/draft-ietf-rtgwg-segment-routing-ti-lfa-08

**Comment by italobusi** [comment]
> Here is the reference: https://datatracker.ietf.org/doc/html/draft-ietf-rtgwg-segment-routing-ti-lfa-08

**[2022-10-07 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-10-07.md)**

- [ ] @italobusi : update the draft with the standard reference
