### ISSUE TITLE
Duplicate figures?

### ISSUE THREAD

**Issue by italobusi** [IETF-TEAS-WG/actn-poi#96]
General suggestion for this section: since the main content of the section is related to fig 2 why do not report again fig. 2 here: it very heavy to come back to figure 2 and reading the same time the text.

_Originally posted by @sergiobelotti in https://github.com/FabioPeruzzini/actn-poi/pull/94#discussion_r912808073_

**Comment by italobusi** [comment]
**[2022-10-18 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-10-18.md)**

Agree with the proposal to duplicate figures, when needed, to simplify the job of the reader

In order to avoid the figures getting out of synch, it is agreed to move to kramdown to develop the next updates of the draft

- [ ] @italobusi move the draft to kramdown
- [ ] @sergiobelotti identify the points where figures are worth to be duplicated

**Comment by italobusi** [comment]
Wait after merging PR #107

**Comment by sergiobelotti** [comment]
> **[2022-10-18 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-10-18.md)**
> 
> Agree with the proposal to duplicate figures, when needed, to simplify the job of the reader
> 
> In order to avoid the figures getting out of synch, it is agreed to move to kramdown to develop the next updates of the draft
> 
> * [ ]  @italobusi move the draft to kramdown
> * [ ]  @sergiobelotti identify the points where figures are worth to be duplicated
For my AP:
Section 4,4, when an example is pointing a path represented in figure 2 .
Section 5 , where both figure 2 and Figure 3 is recalled since all the text is pointing to both the figures and without them is very difficult to understand the "path" text is pointing.

**Comment by sergiobelotti** [comment]
> **[2022-10-18 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-10-18.md)**
> 
> Agree with the proposal to duplicate figures, when needed, to simplify the job of the reader
> 
> In order to avoid the figures getting out of synch, it is agreed to move to kramdown to develop the next updates of the draft
> 
> * [ ]  @italobusi move the draft to kramdown
> * [ ]  @sergiobelotti identify the points where figures are worth to be duplicated
For my AP:
Section 4,4, when an example is pointing a path represented in figure 2 .
Section 5 , where both figure 2 and Figure 3 is recalled since all the text is pointing to both the figures and without them is very difficult to understand the "path" text is pointing.

**Comment by italobusi** [comment]
Ok, I will do as soon as the draft is moved to kramdown

**Comment by italobusi** [comment]
I think this issue can be closed with PR #117 (which has been already merged)

@sergiobelotti : what do you think?

**Comment by italobusi** [comment]
**[2024-06-04 ACTN POI Call](https://github.com/IETF-TEAS-WG/actn-poi/wiki/June-4,-2024)**

Agreed to close this issue since it has been already resolved by PR #117 (which has been already merged)
